### ISSUE TITLE
Revisão de "Manipulating Stirings"

### ISSUE THREAD

**Issue by fccoelho** [felipelmc/PH-Translations#1]
Oi @felipelmc

Sua tradução está bem de acordo com o texto original.
No entanto, vou apontar alguns pontos em que o original está "Errado" na forma como explica algumas coisas e também algumas sugestões de melhorias na forma como texto original explica algo.

- [x]  Na frase `...deve ter aprendido que é necessário declarar ou digitar variáveis...`, ao invés de `digitar`, deveria  usar `tipar`. Mas como este verbo não existe em português, acho melhor escrever `especificar os tipos das variáveis`;
- [x] Na frase `Nesse exemplo, a string "mensagem1" recebe o conteúdo "olá mundo"` o correto seria dizer `a variável *mensagem1* recebe o conteúdo "Olá mundo". Não podemos confundir a variável com seu conteúdo;
- [x] Na explicação do operador de multiplicação, corrigir  "duma" para "de uma". Além disso, seria mais preciso dizer que o operador de multiplicações faze uma concatenação repetida da mesma string...Mas isso é apenas uma sugestão para o texto original.
- [x] Na explicação do operador += novamente corrigir o "duma" como indicado acima.
- [x] Na explicação de Métodos, é errado dizer que métodos são algo que vem pré-instalado. Método são parte da implementação de strings e não podem ser instalados ou desinstalados... Novamente o texto original é que não é muito correto. Aliás, o primeiro exemplo dado, `len` não é um método des string, mas uma função built-in que se aplica a qualquer tipo que possua comprimento...
- [x] Na explicação de `find`: corrigir "numa"  para "em uma";
- [x] No mais, apenas corrigir outras ocorrências de "numa" e "duma"

**Comment by felipelmc** [comment]
Olá @fccoelho! Muito obrigado pela revisão, professor. De fato (e obrigado por chamar minha atenção para isso) o texto original comete alguns erros conceituais. Depois irei sugerir que seja feita uma revisão da lição original também. Quanto aos casos de "numa" e "duma", trata-se de uma forma de aproximar a linguagem da tradução ao português de Portugal, já que há a pretensão de se utilizar as lições do PH tanto aqui no Brasil quanto por lá. Peço desculpas por não ter avisado isso antes.

No mais, muito obrigado pela revisão atenta e pela disponibilidade!
